### ISSUE TITLE
failed 141 (0x8d) 'unknown error code'

### ISSUE THREAD

**Issue by jwoertink** [dinodeck/dinodeck#17]
After running through the `advanced-combat-3` tutorial for the RPG book, I ran the program and got this error:

```text
[14:09PM] advanced-combat-3$ ./dinodeck_mac
2019-02-27 19:13:35.138 dinodeck_mac[99291:10380275] *** CFMessagePort: bootstrap_register(): failed 141 (0x8d) 'unknown error code', port = 0x5303, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2019-02-27 19:13:35.262 dinodeck_mac[99291:10380276] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection invalid
```

The `advanced-combat-3-solution` project throws the same exception.

**Comment by balaam** [comment]
Is that the only message?

It looks vaguely networking related and the only bit of Dinodeck that deals with that is some code to let it interact with an IDE. 

I'm not at my home computer to check but if `webserver = false` isn't in the settings.lua file for those examples, try adding it.

**Comment by jwoertink** [comment]
This was the only output. It just hung after that. I thought the same thing about the networking so I tried setting webserver to false and that didn't work. I also don't use any IDE (vim for the win 😆 ).

**Comment by balaam** [comment]
Ah, ok I'll try on a couple of macs this weekend and see if I can get that same crash!

**Comment by balaam** [comment]
[advanced-combat-3.zip](https://github.com/dinodeck/dinodeck/files/2924743/advanced-combat-3.zip)
This version I have worked locally for me. I'm uploading it here so I can try it on one more machine. But feel to give a go too it you like.

**Comment by balaam** [comment]
^ I also gave this a go on mac with Mojave 10.14.1 and it was ok. So maybe try this zip and see if that works for you.

**Comment by jwoertink** [comment]
So I rebooted my machine, and mine works now. This must have been a fluke, but that was really weird. I guess I'll close this out since I can't reproduce it now, but thanks for taking a look at it.
