### ISSUE TITLE
Ubuntu / Linux Support

### ISSUE THREAD

**Issue by jdriscoll98** [dinodeck/dinodeck#19]
Running Ubuntu 19.10 with Lua 5.3.4

I am only on the first section of the book, but using wine the dinodeck engine runs on linux platforms. On ubuntu "sudo apt install wine" and then when you want to compile and run a game, run "wine dinodeck_win.exe" and it should work just as it does on windows! 

Most people probably know this already but for those who don't it will save them!

**Comment by jdriscoll98** [comment]
Not an issue, but I didn't know where I could put this for people to see.

**Comment by steelx** [comment]
thanks

**Comment by public-space** [comment]
thank you for this. 
i was looking. 
I"m a bit bummed it doesn't run natively. Even so long in the future. 
But maybe I haven't looked hard enough. 
appreciate the info
